//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreADOAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public string Customer_ID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Customer_City { get; set; }
        public string Customer_Street { get; set; }
        public string Customer_PCode { get; set; }
        public string Customer_email { get; set; }
        public string Customer_phone { get; set; }
    }
}
