//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreADOAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public string Item_ID { get; set; }
        public string Order_ID { get; set; }
        public string Stock_ID { get; set; }
        public string isbn { get; set; }
        public string Supplier_ID { get; set; }
        public string Retail_Price { get; set; }
        public string Qty_sold { get; set; }
    }
}
