//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreADOAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public string Order_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Order_Date { get; set; }
        public string Credit_card_numb { get; set; }
        public string Credit_card_expiry { get; set; }
    }
}
