//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreADOAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stocks
    {
        public string STOCK_ID { get; set; }
        public string isbn { get; set; }
        public string Author_name { get; set; }
        public string Title_name { get; set; }
        public string Publisher_name { get; set; }
        public string Published_year { get; set; }
        public string Supplier_ID { get; set; }
        public string Retail_price { get; set; }
    }
}
