//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreADOAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suppliers
    {
        public string Supplier_ID { get; set; }
        public string Stock_ID { get; set; }
        public string Supplier_name { get; set; }
        public string Supplier_City { get; set; }
        public string Supplier_Street { get; set; }
        public string Supplier_PCode { get; set; }
        public string Supplier_email { get; set; }
        public string Supplier_phone { get; set; }
    }
}
